#!/bin/bash
#
# Usage:
# deepomake_remove_docker_containers_and_images TMP_DIR
#
# Result:
# Terminate the docker links.

if [ $# -ne 1 ]; then
    deepomake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

set -e

TMP_DIR=$1

if [ -f ${TMP_DIR}/containers_to_remove.txt ]; then
    set +e
    docker rm -f `cat ${TMP_DIR}/containers_to_remove.txt` > /dev/null 2>&1
    set -e
fi

if [ -f ${TMP_DIR}/images_to_remove.txt ]; then
    set +e
    docker rmi -f `cat ${TMP_DIR}/images_to_remove.txt` > /dev/null 2>&1
    set -e
fi