#!/bin/bash
#
# Usage:
# MD5=$(deepomake_md5 file)
#
# Result:
# Returns the file's MD5.

if [ $# -lt 1 ]; then
    deepomake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

if [ ! -f "$1" ]; then
    deepomake_fail "$0: File $1 does not exist."
    echo "exit 1"
    exit 1
fi

set -e

if [ `which md5sum | wc -l` = "0" ]; then
    echo "$(md5 $1 | cut -d\  -f 4)"
else
    echo "$(md5sum $1 | cut -d\  -f 1)"
fi
