#!/bin/bash
#
# Usage:
# deepomake_run_docker_command ARGS...
#
# Result:
# Run a docker command.

if [ "${DMAKE_ON_BUILD_SERVER}" = "1" ]; then
    deepomake_run_docker "" "" --rm $*
else
    deepomake_run_docker "" "" --rm -t $*
fi
