#!/bin/bash
#
# Usage:
# dmake_run_docker_command ARGS...
#
# Result:
# Run a docker command.

USER_FLAG=""
if [ ! -z ${DMAKE_UID} ]; then
    USER_FLAG="-u ${DMAKE_UID}"
fi

if [ "${DMAKE_ON_BUILD_SERVER}" = "1" ]; then
    dmake_run_docker "" "" ${USER_FLAG} --rm "$@"
else
    dmake_run_docker "" "" ${USER_FLAG} --rm -t "$@"
fi
