#!/usr/bin/env bash
# Use this script to test if a given TCP host/port are available for a docker link
#
# Usage:
# dmake_wait_for_it_wrapper LINK PORTS
#
# Result:
# Wait for links

if [ $# -ne 2 ]; then
    dmake_fail "$0: Missing arguments"
    exit 1
fi

set -e

LINK=${1}
PORTS=${2}

LINK_NAME_UP=$(echo ${LINK} | tr '[:lower:]' '[:upper:]' | sed 's/-/_/g')

for PORT_RANGE in $(echo ${PORTS} | tr "," "\n"); do
    case "$PORT" in
        */tcp )
        PORT_RANGE=${PORT_RANGE%/*}
        PROTO=TCP
        ;;
        *)
        echoerr "Unknown protocol: ${PORT_RANGE}"
        exit 1
        ;;
    esac
    for PORT in $(eval echo "{$(echo ${PORT_RANGE} | sed "s/-/\.\./")}"); do
        HOST_VAR=${LINK_NAME_UP}_PORT_${PORT}_${PROTO}_ADDR
        HOST_PORT=${!HOST_VAR}:${PORT}
        dmake_wait_for_it $HOST_PORT
    done
done

