#!/bin/bash
#
# Usage:
# dmake_deploy_ssh TMP_DIR APP_NAME USER HOST SSH_PORT

# Result:
# Will deploy on a server via SSH

if [ $# -ne 5 ]; then
    dmake_fail "$0: Wrong arguments"
    echo "exit 1"
    exit 1
fi

set -e

TMP_DIR=$1
APP_NAME=$2
USER=$3
HOST=$4
SSH_PORT=$5

# Start script
chmod +x ${TMP_DIR}/start_app.sh

# Copy to server
ssh -p ${SSH_PORT} -tt -o StrictHostKeyChecking=no ${USER}@${HOST} "rm -rf ~/${APP_NAME}"
echo "Running: scp -r -P ${SSH_PORT} -o StrictHostKeyChecking=no ${TMP_DIR} ${USER}@${HOST}:~/${APP_NAME}"
scp -r -P ${SSH_PORT} -o StrictHostKeyChecking=no ${TMP_DIR} ${USER}@${HOST}:~/${APP_NAME}

CMD="~/${APP_NAME}/start_app.sh"
echo "Running: ssh -p ${SSH_PORT} -tt -o StrictHostKeyChecking=no ${USER}@${HOST} \"sudo $CMD\""
ssh -p ${SSH_PORT} -tt -o StrictHostKeyChecking=no ${USER}@${HOST} "sudo $CMD"

