#!/bin/bash
#
# Usage:
# dmake_check_services [ARGS...]
#
# Result:
# Check the service passed as arguments are still running

if [ -z "${DMAKE_TMP_DIR}" ]; then
    dmake_fail "Missing environment variable DMAKE_TMP_DIR"
    exit 1
fi

set -e

IDS=""
for SERVICE in "$@"; do
    LINE=`cat ${DMAKE_TMP_DIR}/daemon_ids.txt | grep " ${SERVICE}\$"`
    if [ -z "${LINE}" ]; then
        dmake_fail "Unexpected error: unknown service ${SERVICE}"
        exit 1
    fi
    ID=`echo ${LINE} | cut -d\  -f 1`
    IDS="${IDS} ${ID}"
done

dmake_check_daemons id $IDS
