#!/bin/bash
#
# Usage:
# dmake_run_docker_command ARGS...
#
# Result:
# Run a docker command.

OPTS="-u $(id -u):$(id -g) --rm"
if [ "${DMAKE_ON_BUILD_SERVER}" = "1" ]; then
    dmake_run_docker "" "" ${OPTS} "$@"
else
    dmake_run_docker "" "" ${OPTS} -t "$@"
fi
