#!/bin/bash
#
# Usage:
# dmake_check_services [ARGS...]
#
# Result:
# Check the service passed as arguments are still running

if [ -z "${DMAKE_TMP_DIR}" ]; then
    dmake_fail "Missing environment variable DMAKE_TMP_DIR"
    exit 1
fi

set -e

for SERVICE in "$@"; do
    LINE=`cat ${DMAKE_TMP_DIR}/daemon_ids.txt | grep " ${SERVICE}\$" || :`
    if [ -z "${LINE}" ]; then
        dmake_fail "Unexpected error: unknown service ${SERVICE}"
        exit 1
    fi
    ID=`echo ${LINE} | cut -d\  -f 1`    
    if [ `docker ps --filter id=${ID} | sed '1d' | wc -l` = 0 ]; then
        >&2 echo -e "Daemon ${SERVICE} quit unexpectedly. Here are the logs:"
        docker logs ${ID}
        exit 1
    fi
done

