#!/bin/bash
#
# Usage:
# dmake_build_base_docker TMP_DIR \
#                         ROOT_IMAGE_NAME \
#                         ROOT_IMAGE_DIGEST \
#                         DOCKER_IMAGE_NAME \
#                         DOCKER_IMAGE_TAG \
#                         DMAKE_DIGEST
#
# Result:
# Will build and cache the base docker images with libs.

test "${DMAKE_DEBUG}" = "1" && set -x

if [ $# -ne 6 ]; then
    dmake_fail "$0: Wrong arguments"
    echo "exit 1"
    exit 1
fi

set -e

TMP_DIR=$1; shift
ROOT_IMAGE_NAME=$1; shift
ROOT_IMAGE_DIGEST=$1; shift
DOCKER_IMAGE_NAME=$1; shift
DOCKER_IMAGE_TAG=$1; shift
DMAKE_DIGEST=$1; shift


function docker_get_image_id() {
  docker image ls "$1" --format '{{.ID}}'
}

BASE_IMAGE="${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
ROOT_IMAGE_NAME="${ROOT_IMAGE_NAME%:*}"  # strip tag if exists: we use the digest instead

# Avoid multiple rebuilds of the same base image in parallel
LOCK="/tmp/dmake-build-docker-base-image-${BASE_IMAGE//\//_}.lock"  # replace `/` by `_` in base image name
LOCK_TIMEOUT=600
if command -v flock>/dev/null 2>&1; then
  LOCK=${LOCK}.flock
  exec 9>${LOCK}
  trap "rm -f ${LOCK}" INT TERM EXIT
  flock --exclusive --timeout ${LOCK_TIMEOUT} 9
elif command -v lockfile >/dev/null 2>&1; then
    if [ ! -z "${DMAKE_TMP_DIR}" ]; then
        echo ${LOCK} >> ${DMAKE_TMP_DIR}/files_to_remove.txt
    fi
    trap "rm -f ${LOCK}" INT TERM EXIT
    lockfile -1 -l ${LOCK_TIMEOUT} ${LOCK}
fi


# Check if base image already exists
echo "Checking cache for docker base image (${BASE_IMAGE})"
# first locally
BASE_IMAGE_ID=$(docker_get_image_id $BASE_IMAGE)
if [ -z "${BASE_IMAGE_ID}" ]; then
  # then remotely
  if [[ "${BASE_IMAGE}" =~ .+/.+ ]]; then
    docker pull $BASE_IMAGE || :
  fi
  BASE_IMAGE_ID=$(docker_get_image_id $BASE_IMAGE)
fi

# Check if we need to re-build
if [ -z "${BASE_IMAGE_ID}" ]; then
    echo "Docker base image not found in cache, building it (${BASE_IMAGE})"

    if [ `uname` = "Darwin" ] && [ ! -z "${DMAKE_SSH_KEY}" ]; then
        OTHER_OPTS="-v ${DMAKE_SSH_KEY}:/key"
    fi

    if [ ! -z "$SSH_AUTH_SOCK" ]; then
        SSH_AUTH_SOCK_VOLUME="-v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK"
    fi

    DOCKER_RUN_ARGS=( run
                      -u 0
                      --cidfile ${TMP_DIR}/cid.txt $SSH_AUTH_SOCK_VOLUME
                      -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK
                      -v ${TMP_DIR}:/base_volume
                      ${OTHER_OPTS}
                      --entrypoint /bin/bash
                      ${ROOT_IMAGE_NAME}@${ROOT_IMAGE_DIGEST}
                      -c "bash /base_volume/make_base.sh"
                    )

    echo "Executing docker ${DOCKER_RUN_ARGS[@]}"

    rm -f ${TMP_DIR}/cid.txt
    docker "${DOCKER_RUN_ARGS[@]}"

    CID=`cat ${TMP_DIR}/cid.txt`
    if [ ! -z "${DMAKE_TMP_DIR}" ]; then
        echo ${CID} >> ${DMAKE_TMP_DIR}/containers_to_remove.txt
    fi

    # We commit the container into the base image
    docker commit --change='CMD ["/bin/bash"]' ${CID} ${BASE_IMAGE}

    if [[ "${DOCKER_IMAGE_NAME}" =~ .+/.+ ]]; then
        echo "Pushing ${BASE_IMAGE}"
        docker push ${BASE_IMAGE}
    fi
else
    echo "Docker base image found in cache, using it (${BASE_IMAGE})"
fi
