#!/bin/bash
#
# Usage:
# dmake_clean TMP_DIR
#
# Result:
# Clean directory created with dmake_make_tmp_dir and linked dockers

if [ $# -ne 1 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

set -e

TMP_DIR=$1

if [ -f ${TMP_DIR}/files_to_remove.txt ]; then
    cat ${TMP_DIR}/files_to_remove.txt | xargs -n 1 rm -rf
fi

dmake_remove_docker_containers_and_images ${TMP_DIR}

rm -rf ${TMP_DIR}

