#!/bin/bash
#
# Usage:
# MD5=$(dmake_copy source/path target/path)
#
# Result:
# Copy a directory to the given destination and creates the directories if necessary.
# Returns the file's MD5 or an aggregate md5 if it is a directory.

test "${DMAKE_DEBUG}" = "1" && set -x

if [ $# -lt 2 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

if [ ! -e "$1" ]; then
    dmake_fail "$0: Path $1 does not exist."
    echo "exit 1"
    exit 1
fi

set -e

SOURCE_PATH=$1
TARGET_PATH=$2
mkdir -p $(dirname ${TARGET_PATH})
cp -rL ${SOURCE_PATH} ${TARGET_PATH}

dmake_md5 ${TARGET_PATH}
