#!/bin/bash
#
# Usage:
# MD5=$(dmake_md5 file)
#
# Result:
# Returns the file's MD5.

if [ $# -lt 1 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

if [ ! -e "$1" ]; then
    dmake_fail "$0: File or directory $1 does not exist."
    echo "exit 1"
    exit 1
fi

set -e

# Command get md5 from piped list of files
if [ `which md5sum | wc -l` = "0" ]; then
    # MacOS compatibility
    CMD="md5"
    COLUMN="4"
else
    # Linux
    CMD="md5sum"
    COLUMN="1"
fi

if [ -f $1 ]; then
    # For files, directly get the md5
    echo $($CMD $1 | cut -d ' ' -f $COLUMN)
else
    # For a directory, it hashes the list of MD5s
    echo $(dmake_find $1 -type f -print0 | xargs -0 $CMD | cut -d ' ' -f $COLUMN | $CMD)
fi


