#!/bin/bash
#
# Usage:
# dmake_build_docker TMP_DIR NAME
#
# Result:
# Build a docker given a ${TMP_DIR}/Dockerfile

if [ $# -ne 2 ]; then
    dmake_fail "$0: Missing arguments"
    exit 1
fi

if [ -z "${DMAKE_TMP_DIR}" ]; then
    dmake_fail "Missing environment variable DMAKE_TMP_DIR"
    exit 1
fi

set -e

TMP_DIR=$1
NAME=$2

cd ${TMP_DIR}

docker build -t ${NAME} .
echo ${NAME} >> ${DMAKE_TMP_DIR}/images_to_remove.txt