#!/bin/bash
#
# Usage:
# ID=$(dmake_get_last_docker_image_id IMAGE)
#
# Result:
# Return an up-to-date ID of the docker image 

if [ $# -ne 1 ]; then
    dmake_fail "$0: Missing image name"
    echo "exit 1"
    exit 1
fi

set -e

IMAGE=$1

function docker_get_image_id() {
    echo `docker images | sed "1d" | sed "s/  */ /g" | cut -d ' ' -f 1-3 | sed "s/ /:/" | grep "$1 " | cut -d ' ' -f 2`
}

docker pull ${IMAGE} > /dev/null || :

ID_ROOT=$(docker_get_image_id ${IMAGE})
if [ -z "${ID_ROOT}" ]; then
    dmake_fail "Could not find root image: ${IMAGE}"
fi

echo $ID_ROOT