#!/bin/bash
#
# Usage:
# dmake_check_daemons FILTER_TYPE [ARGS...]
#
# Result:
# Check the daemons passed as arguments are still running

if [ $# -lt 1 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

set -e

FILTER_TYPE=$1
shift 1

for FILTER in "$@"; do
    if [ `docker ps --filter ${FILTER_TYPE}=${FILTER} | sed '1d' | wc -l` = 0 ]; then
        >&2 echo -e "Daemon ${FILTER} quit unexpectedly. Here are the logs:"
        docker logs ${FILTER}
        exit 1
    fi
done

