dmake_version: 0.1
app_name: dmake-tutorial

env:
  default:
    variables:
      NAME: ${REPO_SANITIZED}-${BRANCH_SANITIZED}-${BUILD}
      IMAGE_TAG_PREFIX: ${IMAGE_TAG_PREFIX}

docker:
  root_image:
    name: ubuntu
    tag: 16.04

services:
  - service_name: e2e
    needed_services:
     - service_name: web
       link_name: web
       env_exports:
         WEB_URL: http://web:8000
    config:
      docker_image:
        build:
          context: .
          dockerfile: ./deploy/Dockerfile
    tests:
      commands:
        - echo running tutorial from ${NAME} with image tag prefix ${IMAGE_TAG_PREFIX}
        - curl -sSf "${WEB_URL}/api/factorial/?n=5"
      timeout: 5
