#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

import sys
import argcomplete
import dmake.common as common
from dmake.common import DMakeException

import dmake.cli as cli

if __name__ == "__main__":
    try:
        # Parse command args
        argcomplete.autocomplete(cli.argparser, default_completer=None)
        args = cli.argparser.parse_args()
        common.init(args)
        args.func(args)
    except DMakeException as e:
        print('ERROR: ' + str(e))
        sys.exit(1)
