#!/bin/bash
#
# Usage:
# TMP=$(dmake_make_tmp_dir)
#
# Result:
# Create a fresh temporary directory and returns its path

test "${DMAKE_DEBUG}" = "1" && set -x

set -e

NAME=$1

while [ 1 ]; do
    # Trailing slash allows to have correct local path when DMAKE_TMP_DIR is not defined
    TMP=dmake_tmp_`date +%s%N`_`printf "%05d" $RANDOM`_${NAME}/
    if [ -z "${DMAKE_TMP_DIR}" ]; then
        if [ `uname` = "Darwin" ]; then
            TMP=/private/tmp/$TMP
        else
            TMP=/tmp/$TMP
        fi
    else
        TMP=${DMAKE_TMP_DIR}$TMP
    fi
    if [ ! -d $TMP ]; then
        mkdir -p $TMP
        echo $TMP
        if [ ! -z "${DMAKE_TMP_DIR}" ]; then
            echo $TMP >> ${DMAKE_TMP_DIR}/files_to_remove.txt
        fi
        exit 0
    fi
done
