#!/bin/bash
#
# Usage:
# dmake_remove_docker_containers_and_images TMP_DIR
#
# Result:
# Remove containers, images and volumes to remove.

test "${DMAKE_DEBUG}" = "1" && set -x

if [ $# -ne 1 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

set -e

TMP_DIR=$1

if [ "${DMAKE_NO_DOCKER_CLEANUP}" = "1" ]; then
    exit 0;
fi

if [ -f ${TMP_DIR}/containers_to_remove.txt ]; then
    set +e
    docker rm -f `cat ${TMP_DIR}/containers_to_remove.txt` > /dev/null 2>&1
    set -e
fi

if [ -f ${TMP_DIR}/images_to_remove.txt ]; then
    set +e
    docker rmi -f `cat ${TMP_DIR}/images_to_remove.txt` > /dev/null 2>&1
    set -e
fi

if [ -f ${TMP_DIR}/shared_volumes_to_remove.txt ]; then
    set +e
    docker volume rm -f `cat ${TMP_DIR}/shared_volumes_to_remove.txt` > /dev/null 2>&1
    set -e
fi
