#!/bin/bash
#
# Usage:
# dmake_run_docker_command ARGS...
#
# Result:
# Run a docker command.

test "${DMAKE_DEBUG}" = "1" && set -x

USER_FLAG=""
if [ ! -z "${DMAKE_UID}" ]; then
    USER_FLAG="-u ${DMAKE_UID}"
fi

if [ -t 1 ]; then
    dmake_run_docker "" "" ${USER_FLAG} --rm -t "$@"
else
    dmake_run_docker "" "" ${USER_FLAG} --rm "$@"
fi
