#!/bin/bash
#
# Usage:
# dmake_check_daemons FILTER_TYPE [ARGS...]
#
# Result:
# Check the daemons passed as arguments are still running

test "${DMAKE_DEBUG}" = "1" && set -x

if [ $# -lt 1 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

set -e

FILTER_TYPE=$1
shift 1

for FILTER in "$@"; do
    if [ `docker ps --filter ${FILTER_TYPE}=${FILTER} | sed '1d' | wc -l` = 0 ]; then
        exec 1>&2
        echo "Daemon ${FILTER} quit unexpectedly. Here are the status and logs:"
        docker inspect ${FILTER} --format '{{json .State}}'
        echo "-----BEGIN LOGS-----"
        docker logs ${FILTER}
        echo "-----END LOGS-----"
        exit 1
    fi
done
