#!/bin/bash
#
# Usage:
# dmake_find [ARGS ...]
#
# Result:
# Same command as find except it does not fail when it does not have permissions
# on files or directories, which is usually due to file gneeration in docker.
# ARGS are the same as the usual find.

test "${DMAKE_DEBUG}" = "1" && set -x

{ LC_ALL=C find "$@" 2>&1 1>&3 | { grep -v 'Permission denied' 1>&2; [ $? -eq 1 ]; } } 3>&1
