#!/bin/bash
#
# Usage:
# dmake_run_credential_server
#
# Result:
# Run a local credential server to server ssh key

test "${DMAKE_DEBUG}" = "1" && set -x

set -e

if [ `docker ps -f name=credential_server -f status=running | sed 1d | wc -l` -gt "0" ]; then
    exit 0
fi

docker rm credential_server > /dev/null 2> /dev/null || :

if [ `docker images | grep credential_server | wc -l` = "0" ]; then
    make -C $(dirname $0)/../credential_server build
fi

# Change host of docker machine
make -C $(dirname $0)/../credential_server run

sleep 1
if [ `docker ps -f name=credential_server -f status=running | sed 1d | wc -l` = "0" ]; then
    dmake_fail "Could not start the credential server !"
    exit 1
fi
