#!/bin/bash
#
# Usage:
# dmake_build_docker CONTEXT_DIR IMAGE_NAME ARGS...
#
# Result:
# Build a docker image named ${IMAGE_NAME} using build context ${CONTEXT_DIR}

test "${DMAKE_DEBUG}" = "1" && set -x
test "${DMAKE_DEBUG}" = "1" && DOCKER_BUILD_DEBUG=1


if [ $# -lt 2 ]; then
    dmake_fail "$0: Missing arguments"
    exit 1
fi

if [ -z "${DMAKE_TMP_DIR}" ]; then
    dmake_fail "Missing environment variable DMAKE_TMP_DIR"
    exit 1
fi

set -e

CONTEXT_DIR=$1
IMAGE_NAME=$2
shift 2

BUILD_EXTRA_ARGS=()
# test if buildkit for debug
if [ "${DOCKER_BUILD_DEBUG}" = "1" ] && docker image build --help | grep -q -- --progress; then
  BUILD_EXTRA_ARGS+=("--progress=plain")
fi

docker ${DOCKER_BUILD_DEBUG:+--debug} image build "${BUILD_EXTRA_ARGS[@]}" "$@" --tag ${IMAGE_NAME} ${CONTEXT_DIR}
echo ${IMAGE_NAME} >> ${DMAKE_TMP_DIR}/images_to_remove.txt
