#!/bin/bash
#
# Usage:
# LINKS=$(dmake_return_docker_links APP_NAME [ARGS...])
#
# Result:
# Return the links for container previously launched with dmake_run_docker_link, e.g. "--link <container_id>:LINK_NAME"

test "${DMAKE_DEBUG}" = "1" && set -x

if [ $# -lt 1 ]; then
    dmake_fail "$0: Missing arguments"
    echo "exit 1"
    exit 1
fi

if [ -z "${DMAKE_TMP_DIR}" ]; then
    dmake_fail "Missing environment variable DMAKE_TMP_DIR"
    exit 1
fi

set -e

APP_NAME=$1
shift 1

CACHE_DIR="${DMAKE_TMP_DIR}/links/${APP_NAME}"

LINK_OPTS=( )
for LINK_NAME in "$@"; do
    ID_FILE="${CACHE_DIR}/${LINK_NAME}.id"
    if [ -f "${ID_FILE}" ]; then
        dmake_check_daemons id ${CONTAINER_ID}
        ID=`cat ${ID_FILE}`
        LINK_OPTS+=( --link=${ID}:${LINK_NAME} )
    else
        dmake_fail "Unexpected error: missing link ${LINK_NAME}"
        exit 1
    fi
done
echo "${LINK_OPTS[@]}"
